from flask_wtf import FlaskForm
from wtforms import (StringField, TextAreaField, IntegerField, BooleanField, RadioField)
from wtforms.validators import InputRequired


class HeroInputForm(FlaskForm):
    your_hero = StringField("Your Hero And Summon Cost: ", validators=[InputRequired()])
    your_hero_realm = RadioField("Your Hero Realm:  ", choices=["Serendale", "Serendale 2", "Crystalvale"], validators = [InputRequired()])
    sd_candidate_list = TextAreaField("Serendale Candidates And Summon Costs: ")
    sd_2_candidate_list = TextAreaField("Serendale 2 Candidates And Summon Costs: ")
    cv_candidate_list = TextAreaField("Crystalvale Candidates And Summon Costs: ")


class MatsInputForm(FlaskForm):
    kingdom = RadioField("Kingdom ", choices=["Serendale", "Crystalvale"], validators=[InputRequired()])
    transaction_cost = IntegerField("Klay/Jewel", default=0) 
    crystal = IntegerField("Crystal ", default=0)
    jewel = IntegerField("Jewel ", default=0)
    tears = IntegerField("Tears ", default=0)
    shvas_runes = IntegerField("Shvas Rune ", default=0)
    moksha_runes = IntegerField("Moksha Rune ", default=0)
    yellow_egg = IntegerField("Yellow Egg ", default=0)
    blue_egg = IntegerField("Blue Egg ", default=0)
    grey_egg = IntegerField("Grey Egg ", default=0)
    green_egg = IntegerField("Green Egg ", default=0)
    yellow_egg = IntegerField("Yellow Egg ", default=0)
    gold = IntegerField("Gold ", default=0)
    bloater = IntegerField("Bloater ", default=0)
    ironscale = IntegerField("Ironscale ", default=0)
    lantern_eye = IntegerField("Lantern-Eye ", default=0)
    redgill = IntegerField("Redgill ", default=0)
    silverfin = IntegerField("Silverfin ", default=0)
    sailfish = IntegerField("Sailfish ", default=0)
    shimmerskin = IntegerField("Shimmerskin ", default=0)
    frost_bloater = IntegerField("Frost Bloater ", default=0)
    speckle_tail = IntegerField("Speckle Tail ", default=0)
    three_eyed_eel = IntegerField("Three-Eyed Eel ", default=0)
    king_pincer = IntegerField("King Pincer ", default=0)
    ragweed = IntegerField("Ragweed ", default=0)
    rockroot = IntegerField("Rockroot ", default=0)
    redleaf = IntegerField("Redleaf ", default=0)
    darkweed = IntegerField("Darkweed ", default=0)
    ambertaffy = IntegerField("Ambertaffy ", default=0)
    goldvein = IntegerField("Goldvein", default=0)
    swift_thistle = IntegerField("Swift-Thistle", default=0)
    frost_drum = IntegerField("Frost Drum ", default=0)
    knaproot = IntegerField("Knaproot ", default=0)
    shaggy_cap = IntegerField("Shaggy Cap ", default=0)
    skunkshade = IntegerField("Skunkshade ", default=0)
    bluestem = IntegerField("Bluestem ", default=0)
    spiderfruit = IntegerField("Spiderfruit ", default=0)
    milkweed = IntegerField("Milkweed ", default=0)
    might_stone = IntegerField("Might Stone ", default=0)
    swiftness_stone = IntegerField("Swiftness Stone ", default=0)
    fortitude_stone = IntegerField("Fortitude Stone ", default=0)
    insight_stone = IntegerField("Insight Stone ", default=0)
    finesse_stone = IntegerField("Finesse Stone ", default=0)
    vigor_stone = IntegerField("Vigor Stone ", default=0)
    wit_stone = IntegerField("Wit Stone ", default=0)
    fortune_stone = IntegerField("Fortune Stone ", default=0)

